### PR TITLE
fix PD timing resolution parameters

### PR DESCRIPTION
**Pull request by YujiOkajima**
As I described in #82, the timing resolution parameters of HPD should be fixed and I analyzed with new analysis method.

### CODE REVIEW

**Comment by eosullivan** [comment]
It will be a bit confusing if we have different fitting methods for the box & line and the HPDs. Even though this new method doesn't change the box & line results, I wonder if it is worth using just so we are consistent. Also, is there some way to make the box & line function match the data better? Are you still investigating?

**Comment by YujiOkajima** [comment]
@eosullivan  I have analyzed the Box and Line PMT result with the same fitting method as HPD as a reference.
The result is shown in #82. 
The timing resolution of Box & Line PMT with new fitting method seemed to be better than current parameters.
The parameters of Box & Line PMT with new method has been already analyzed.
So, I can change it immediately.

I am not searching for new analysis method to make the Box & Line PMT function match the data better now.

If we search for more suitable analysis method, I have 3 ideas below.

One idea for making the Box & Line PMT function match the data is use more narrow width qbin.
The timing resolution of the new photodetectors are analyzed after TQ correction, but if the dependence is still remained, the timing resolution will be change.

another idea is changing TQ correction method. In current TQ correction, the TQ map is corrected based on timing distribution peak. The peak of EMG distribution is based on the Gaussian peak and 1/lambda.
So, even if the EMG peak is fixed, the Gaussian peak will be changed when the charge is changed. I think the difference of Gaussian peak is possible to make the timing resolution worse.
Therefore, I think correction of TQmap based on the Gaussian peak of EMG is possible to be better for analysis than current analysis.

last candidate is searching for more suitable fitting function.

**Comment by YujiOkajima** [comment]
Based on the result of analysis with fitting of 1/lambda, the parameter of lambda was changed.
The figure below shows the result of 1/lambda fitting.
boxandline_newlambdainvert
From this figure, the lambda parameters were changed to (0.4113, 0.07827)

**Comment by eosullivan** [comment]
Sorry for the delay in getting this merged. I still don't really understand how switching to 1/lambda improved the fit. Perhaps the improvement came mostly from the finer binning. Either way, it's safe to say that these new parameters are an improvement for the case of the HPDs so I'll merge this in. We should continue to think about how to improve the box and line fit.

**Pull request merged**
