### PR TITLE
Change HPD parameters to reflect the results from new measurements

### PR DESCRIPTION
**Pull request by YujiOkajima**
This request is modification of #75.  (Remove old HPD parameters and one geometry with 14% photo coverage HPD, and fix conversion factor)
In order to clear the commit log, I newly requested this code.

My analysis method of the conversion factor of dark noise had a mistake (take pmt hit count in 310 ns timing window to that in 300 ns timing window), and the conversion factor was fixed (conversion factor for HPD: 1.119).

And I validated the dark rate again and modified the slide  I uploaded by using this result.
https://dl.dropboxusercontent.com/u/61208795/NewHPD_Implementation.pdf
(validation result about dark rate: slide page.7,8)
From this validation, the dark rate seems to work correctly.

### CODE REVIEW

**Comment by eosullivan** [comment]
Okajima, sorry I was maybe not clear. Please remove all new detector configurations from this pull request so that the only code changes are adding in the HPDs. Don't worry about making a new pull request for it. It is easier to find conversations about old pull requests if we just have a single pull request per issue.

**Comment by YujiOkajima** [comment]
I removed the geometry implemented.

**Comment by eosullivan** [comment]
Ok, this looks fine to me. @YujiOkajima, are you all finished with your validation? Do you think this is ready to merge in?

**Comment by YujiOkajima** [comment]
The validation of modified parameters, which is 1p.e. distribution, dark noise, and timing resolution, has been finished.
(Validation results: pull request #75 and #76, and page.7 of https://dl.dropboxusercontent.com/u/61208795/Description_hittime_validation.pdf)
So, I think this code is ready.

**Comment by cwwalter** [comment]
Can someone also edit the title of this PR before it gets merged to remove the new geometry part?  That will make it better for understanding the history.

**Comment by YujiOkajima** [comment]
I fixed the title of pull request

**Pull request merged**
