### PR TITLE
iteration in verification_HitsChargeTime.C

### PR DESCRIPTION
**Pull request by JostMigenda**
This fixes part 1 of #169

### CODE REVIEW

**Comment by tdealtry** [comment]
Hi @JostMigenda Surely min(nevent,nevent2) is the safest way to loop?

**Comment by JostMigenda** [comment]
Hi @tdealtry! `nevents2` is the number of events in the second root file, so I don’t see how this is in any way unsafe.

There’s an argument to be made for comparing the first `min(nevents,nevents2)` events of both files, since the whole point of that script is to verify that to different data files contain identical events.
On the other hand, if a user compares two data files with a different number of events, that probably means that they mixed up two files (or simply mistyped), just like I did when I discovered this problem. In that case, it would be best to show this problem to the user. (We could even make it more obvious by returning early if `nevents` ≠ `nevents2`.)

**Comment by tdealtry** [comment]
Sorry, my mistake. I forgot how the comparison was done - it's a loop over file1 then a separate loop over file 2 (not a loop over both files simultaneously as I assumed).
Some warning message (or early exit) when the number of entries in the two files are different would be a good idea.

**Comment by JostMigenda** [comment]
e004f2c...d6a921a are mostly to make the code easier to read/understand and remove unnecessary code. The early return will be added in the next commit.

**Comment by eosullivan** [comment]
I don't like that we've removed some functionality of the script by removing a default filename. You could always specify your own filename, but it would be nice if it could be automatically set up to work with the electrontest.mac as specified in the README in the verification-test-scripts/ directory. If this that README is out of date (I think it is) then we should change that. Also, I think we should put out a warning message if the file sizes don't match, but not exit the program. Put it somewhere readable, like where the ks stats are output. I can see some reasons why people might use files of different sizes, like if they only care if the first event matches, for example.

**Comment by JostMigenda** [comment]
I didn’t remove the default filenames – just moved them up to line 6, so we don’t have to check ourselves whether the user provides their own filenames; instead, this now gets done for us. Running the script without explicitly giving filenames still works for me, same as before.

Checking whether the first event matches is a realistic use case, you’re right. How about moving the early return to after the comparison of the first events (but before looping through all events)? I can’t think of a use case for comparing root files with a different number of events, so I would avoid doing that.

**Comment by eosullivan** [comment]
Ok, an early return after checking the first event sounds reasonable, along with a descriptive exit message that says that only the first events are being compared since the file sizes do not match.

**Pull request merged**
