### PR TITLE
Make the default SKI digitizer integration window more realistic

### PR DESCRIPTION
**Pull request by tdealtry**
Change the default SKI digitizer integration window from 200 ns to the value of the actual integration window used in SKI electronics: 400 ns.
This is a partial fix of #112

### CODE REVIEW

**Comment by eosullivan** [comment]
Have you done any tests to show how this change affects on the physics output of the code? After making this change, are we still able to match SKDETSIM? Also, was there any resolution to your finding that the digitizer integration window is 300 ns in SKDETSIM?

**Comment by tdealtry** [comment]
Comparing 200 ns and 400 ns [dealtry_2016_01_21_wcsim.pdf](https://github.com/WCSim/WCSim/files/99514/dealtry_2016_01_21_wcsim.pdf)
* The nhit & ndigit distributions look fine
* The digit time distributions look ok, but the breakdown (noise-only vs Cherenkov-only vs mix) is different - there is migration to the 'mix' category (as expected)
* There's a small difference in the trigger times at low energy, on the same order as we saw before (a few 10s ns)

I'll chase people up about SKDETSIM in Kashiwa. My current best guess that SKDETSIM uses 300 ns is exactly that - a guess. To reiterate, I currently have no access to the complete SKDETSIM source code, I can't run it, and the files I do have are from 2010.

**Comment by cwwalter** [comment]
> To reiterate, I currently have no access to the complete SKDETSIM source code, I can't run it, and the files I do have are from 2010.

Just as a reminder you can get a suketto account at Kamioka as a HK member.

**Comment by tdealtry** [comment]
> Just as a reminder you can get a suketto account at Kamioka as a HK member.

Yep, I applied last week. Just waiting for approval.

**Comment by eosullivan** [comment]
I'm going to hold off on merging this pull request until after the HK meeting. This will give you time to look through SKDETSIM and to ask some SKDETSIM experts at the meeting, and is not so crucial to be in this next release.

**Comment by tdealtry** [comment]
I'm going to close this PR. 200 ns is the value that's been used for the past 5 years for HK studies, so should continue.
We will of course have a more realistic HK digitiser simulation at some point in the future. And requests from SK collaborators  to make the digitiser more realistic are also welcomed

**Pull request closed without merging**
