### PR TITLE
Cosmics generator

### PR DESCRIPTION
**Pull request by P3tru**
This PR add a cosmic generator option, based on SuperK cosmic flux measurements extrapolated on HyperK per default.
This data file is added as "MuonFLux-HyperK-ThetaPhi.dat", but any other data file *in the same format* would work (for example, to use the cosmic flux at SuperK directly).

### CODE REVIEW

**Comment by P3tru** [comment]
Here comes some validation plots for this branch 
[HyperKOD.pdf](https://github.com/WCSim/WCSim/files/1759421/HyperKOD.pdf)

**Comment by tdealtry** [comment]
Thanks for this @P3tru Again it looks like this is included in #297, so please let me know @mahditaani whether to review/merge this, or close it (i.e. whether it's been modified in #297)
Whichever PR it gets merged in, some documentation of the `.dat` format would be great

**Comment by mahditaani** [comment]
Hi @tdealtry, I believe this has been changed slightly since the time it was originally implemented so it is probably best to review #297 instead.

**Comment by tdealtry** [comment]
Thanks @mahditaani Closing this PR

**Pull request closed without merging**
