### PR TITLE
Fix WCBox overlap

### PR DESCRIPTION
**Pull request by kmtsui**
Fix for issue https://github.com/WCSim/WCSim/issues/463

### CODE REVIEW

**Comment by tdealtry** [comment]
Thanks for this @kmtsui It looks good
We'll be able to see the plots this time (failed last time because of another expired key... sorry!)

**Comment by tdealtry** [comment]
[Only changes in the validation](https://wcsim.github.io/Validation/6ba3468ad9d80b7f13c8c7ceb158606bb9f29858/index.html) are for high energy events in WCTE (5 MeV not effected). I think this is what we expected

I'll let @kmtsui & @nickwp take a look at this before merging
(As it's a release-worthing change, please also say whether I should merge #462 at the same time)

**Comment by kmtsui** [comment]
@tdealtry Yes I think it's good to merge https://github.com/WCSim/WCSim/pull/462 at the same time

**Comment by tdealtry** [comment]
Ok great. Please let me know explicitly when you're happy that both PRs are ready to merge

**Comment by kmtsui** [comment]
@tdealtry I think we are ready to merge both PRs

**Pull request merged**
