### PR TITLE
WCSim migration to G4.10 ### TO BE DELETED ### See pull request #202

### PR DESCRIPTION
**Pull request by P3tru**
This is the implementation of G4.10 inside WCSim.

Tests have been run to compare if there is a difference between version of Geant4 9.4.4 and Geant4 10.1.3 and results shows no differences for electrons and muons between [100-1000] MeV by setting the BERTINI physics list by default.
However, changes can be seen in muons at low energy (100 MeV) using the BINARY physics list. As a recommendation by Geant4 developers, the BERTINI physics list is set to the default one in file joboption2.mac.
Some results can be found at http://pprc.qmul.ac.uk/~zsoldos/G4results.pdf
It's worth noticing that the GEISHA models have been depreciated and are now removed from WCSim.

The biggest changes can be found in the WCSimPhysicsList class. Other changes are mainly made to incorporate the new headers for physical constants introduced by Geant4 version 10.

This work is based on Sam Short and Francesca Di Lodovico implementation. See https://github.com/WCSim/WCSim/pull/178

### CODE REVIEW

**Comment by eosullivan** [comment]
Can you also upload the PDF of your verification work directly to here? Personal links have a way of disappearing.

**Comment by P3tru** [comment]
Hi Erin,

 

Yes I think I worked straight on the develop branch of the fork I made of WCSim.

To be completely honest with you it’s the first time I am using git and I don’t know how it works really… Since there is this indentation problem as well, might should I restart again in order to make a clean pull request ? Could you detailed me the procedure ? 

I think what I should do would be to checkout version 1.5.1 again, create a new branch at this point, reimplement the modification (and without touching on the indentation of the other files) and then do a pull request ? Or should I merge the new branch into develop and then pull request ?

 

Apologize for the inconvenience,

Stephane

**Comment by eosullivan** [comment]
Sure, no worries. Consider it a git right-of-passage since I think this happens to everyone the first time they make a pull request. The key is that you do not want to check out version 1.5.1, but want to fork the develop branch. Always do your pull requests from feature branches off the develop branch. I've tried to look at your account to see what went wrong and it looks like you did fork the develop branch as you were supposed to, but perhaps something must have gone awry somewhere to mess up your commit history. 

Anyways, the best thing to fix that as well as the spacing issue, might be to copy your work to a different directory and start fresh. The instructions for how to create your own fork of the WCSim develop branch is [here].(https://github.com/WCSim/WCSim/wiki/Tutorial:-How-to-set-up-GitHub-(in-the-context-of-WCSim)#fork-a-copy-of-the-wcsim-code) You then want to set up a feature branch on which you will make your modifications (see these [instructions](https://github.com/WCSim/WCSim/wiki/How-to-manage-your-branches-and-make-a-pull-request). Make your Geant 4.10 changes on your feature branch and make sure you validate it to ensure it acts like it did before. Then, make a pull request using the instructions also on that page. If you need to update your branch because other commits have gone on to the develop branch since you made your fork, instructions for how to do that can be found [here](https://github.com/WCSim/WCSim/wiki/How-to-Keep-your-Branches-Up-to-Date). If you run into any issues while doing this, email me. I'm at SK, working the night shift, so I'll be keeping somewhat weird hours this week and will be around from 00:30 to 8:30 JST.

**Comment by P3tru** [comment]
Alright thank you very much I should have ask you before how to proceed !

 

I am at the T2K collab meeting at the moment in Tokai, I would try to solve this asap.

 

Cheers,

Stephane

**Comment by eosullivan** [comment]
resolved with pull requests #202 and #211

**Pull request closed without merging**
