### PR TITLE
Implements QE function interpolation in WCSimDetectorConstruction::CreateCombinedPMTQE()

### LINKED ISSUE #323: Interpolation of QE functions required in WCSimDetectorConstruction::CreateCombinedPMTQE()
### Intended behavior

When constructing a detector with multiple PMT types, WCSim invokes [`WCSimDetectorConstruction::CreateCombinedPMTQE()`](https://github.com/WCSim/WCSim/blob/0403225ffb3b22ef25113bd0ae66ab21db952699/src/WCSimDetectorConstruction.cc#L318-L417) to calculate a hybrid quantum efficiency function for the combination of types.  The purpose of the hybrid QE function is to allow a QE check on photons at emission ([in the Stacking Action](https://github.com/WCSim/WCSim/blob/0403225ffb3b22ef25113bd0ae66ab21db952699/src/WCSimStackingAction.cc#L23-L73)) so that they may be efficiently discarded before propagation through the bulk of the detector.  Because it is not know at emission what type of PMT, if any, the photon will hit, a QE function representative of the whole detector is required in order to make such a check.

The apparent intent of the implementation of [`WCSimDetectorConstruction::CreateCombinedPMTQE()`](https://github.com/WCSim/WCSim/blob/0403225ffb3b22ef25113bd0ae66ab21db952699/src/WCSimDetectorConstruction.cc#L318-L417) is to create a hybrid QE function that, for each photon wavelength, is equal to the largest QE of any used PMT type at that wavelength.

### Implementation

The QE(lambda) functions for each PMT type are defined as linear interpolations of parallel arrays of lambda_i and QE_i values.  The domain array of the hybrid QE function, $lambda_k$, is a union of the domain points for each of the individual PMT types.  The range array, QE_k, has the maximum QE_i value for any PMT with lambda_k in its domain array.

### Issue

When the lambda_i arrays of the PMT types are not identical, the hybrid QE_k array values can jump wildly among the PMT types in a way that does not represent the maximum QE efficiency at a given wavelength.

### PR DESCRIPTION
**Pull request by spradlin**
Proposed fix for Issue #323.

### CODE REVIEW

**Comment by spradlin** [comment]
@tdealtry I rebased the source branch for this MR.  I performed tests in local to verify that the current `develop` branch still exhibits the issues described in #323 and that this updated MR does still fix it.

After review and merge, this MR should close #323 .

**Comment by tdealtry** [comment]
The CI is working now, mostly fine. But unfortunately I can't see how to get your branch using the new CI file myself. Can you do something like a `git pull && git push` (I think only changes are to `.github/workflows`, so there shouldn't be any conflicts)

**Comment by spradlin** [comment]
I rebased the source branch to the current head of WCSim:develop.

**Comment by tdealtry** [comment]
This is great. Thanks @spradlin

**Pull request merged**
